@startuml
title Criar e Publicar Rotas de Turismo (Administrador)

start

: Acessa a plataforma;
: Nomeia a rota de turismo;
: Define cada trecho e ponto específico da rota;

repeat
  :Seleciona ponto de interesse da rota;
repeat while (Deseja adicionar mais pontos de interesse?) is (Sim)

:Define tempo de duração da rota;
:Define privacidade da rota;

:Salva informações da rota;
:Publica rota salva;

stop

@enduml
