@startuml
skinparam monochrome true

|Usuário Comum|
:Entrar ou Acessar como Convidado;
:Acessar Página de Eventos;
:Selecionar Cidade (e.g., Tatuí, São Paulo);
:Selecionar Data ou Intervalo de Datas;
:Selecionar Tipo de Acessibilidade (PCD, Pet-Friendly);
:Selecionar Tipo de Evento (Cultural, Festivo);
:Aplicar Filtros;
:Visualizar Resultados Filtrados;
:Selecionar Evento;
:Visualizar Informações Detalhadas (Nome, Data, Local);

@enduml