@startuml
skinparam monochrome true

|Administrador|
:Entrar na Plataforma;
:Autenticar e Autorizar (RBAC);
:Acessar Painel de Gerenciamento de Usuários;
:Visualizar Lista de Usuários;
if (Ação?) then (Adicionar Usuário)
    :Criar Novo Usuário;
    :Adicionar Dados (Nome, E-mail);
    :Selecionar Papel (Administrador, Publicador, Usuário Comum);
    :Confirmar Criação;
    :Notificar Usuário;
else (Editar Usuário)
    :Selecionar Usuário;
    :Atualizar Dados ou Papel;
    :Confirmar Alteração;
    :Notificar Usuário;
else (Excluir Usuário)
    :Selecionar Usuário;
    :Confirmar Exclusão;
    :Remover Conta do Usuário;
    :Notificar Usuário (Opcional);
endif

@enduml